apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xvpcs.aws.platformref.upbound.io
spec:
  group: aws.platformref.upbound.io
  names:
    kind: XVPC
    plural: xvpcs
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              vpcName:
                type: string
            required:
            - vpcName
