apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbuckets.aws.platformref.upbound.io
spec:
  group: aws.platformref.upbound.io
  names:
    kind: XBucket
    plural: xbuckets
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              bucketName:
                type: string
            required:
            - bucketName
